"""Change audio_records table

Revision ID: a267186a0e0d
Revises: f8bc2e7b29df
Create Date: 2023-06-12 02:12:36.705100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a267186a0e0d'
down_revision = 'f8bc2e7b29df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_uuid', sa.Integer(), nullable=False))
    op.alter_column('questions', 'question',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'answer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_questions_id', table_name='questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_questions_id', 'questions', ['id'], unique=False)
    op.alter_column('questions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('questions', 'answer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('questions', 'question',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('questions', 'question_uuid')
    # ### end Alembic commands ###
